- docs/DOCUMENTATION_GUIDE.md
Signed-off-by: Tao liu <liutaoaz@amazon.com>
Adding docs folder and guide file which was used for hosting the design docs.
Resolve #13 
> Add Doc Guide

- config/playground/helm/prod/helm-opensearch-dashboards.yaml
- config/playground/helm/prod/helm-opensearch.yaml
Signed-off-by: Huy Nguyen <wronghuy@amazon.com>
This PR adds prod deployment files, which have mostly been used in the dev environment, with some increased replica counts.
> Adds prod deployment files

- config/playground/cronjobs/metrics/cronjob-healthcheck.yaml
- config/playground/metrics/README.md
- config/playground/metrics/cronjobs/cronjob-healthcheck.yaml
- config/playground/metrics/fluent-bit/fluent-bit.yaml
Add metrics configuration files which was used for playground monitor and alert. 
#50 
> [OpenSearch Playground] Adds metrics configuration files

- MAINTAINERS.md
> [OpenSearch-Anywhere] Adds maintainers.md file

- .github/workflows/deployment-template.yml
- .github/workflows/os-osd-deployment-scheduled.yml
- config/playground/helm/dev/helm-opensearch-dashboards.yaml
- config/playground/helm/preview/helm-opensearch-dashboards.yaml
- config/playground/helm/preview/helm-opensearch.yaml
Add new cluster which will be used for preview and reinvent. OS and OSD was enabled reset by daily.
Test this change by https://github.com/opensearch-project/dashboards-anywhere/actions/runs/3382826885
#95 
> [OpenSearch Playground] Add new cluster and enable auto reset

- .github/workflows/deployment-template.yml
- .github/workflows/os-osd-deployment-scheduled.yml
- config/playground/helm/preview/helm-opensearch-dashboards.yaml
- config/playground/helm/preview/helm-opensearch.yaml
Update preview configuration, use secret instead of openid redirect url. 
#95 
> [OpenSearch Playground] Update preview configuration

- .github/workflows/deployment-template.yml
- .github/workflows/os-osd-deployment-scheduled.yml
- config/playground/helm/dev/helm-opensearch.yaml
- config/playground/metrics/README.md
- config/playground/metrics/logstash/preview/logstash-configmap.yaml
- config/playground/metrics/logstash/preview/logstash.yaml
- config/playground/metrics/tracing/preview/data-prepper.yaml
- config/playground/metrics/tracing/preview/jaeger-agent.yaml
- config/playground/metrics/tracing/preview/otel-collector.yaml
- config/playground/metrics/tracing/preview/otel-config.yaml
Add logstash and tracing to the pipeline, which used for live sample data ingestion for cluster metrics and sample application.
#98 
> [OpenSearch Playground] Add logstash and tracing to the deployment pipeline

- config/playground/helm/preview/helm-opensearch.yaml
- config/playground/metrics/README.md
Update OpenSearch memory and metrics readme for live sample.
#99
> [OpenSearch Playground] Update memory and readme

- config/playground/helm/preview/helm-opensearch-dashboards.yaml
Remove old wizard feature flag as enabled by default already
> [Opensearch reinvent] remove old wizard feature flag

- config/playground/helm/prod/helm-opensearch-dashboards.yaml
- config/playground/helm/prod/helm-opensearch.yaml
Update prod configuration to remove old feature flag and change storage size to 50G
N/A
> [OpenSearch Playground] Update prod configuration

- config/playground/helm/preview/helm-opensearch.yaml
Update sql query permission which allows to run sql join query
N/A
> [OpenSearch Playground] Update sql query permission which allows to run sql join query

- config/playground/helm/preview/helm-opensearch.yaml
Add application_analytics change to opensearch image. 
N/A
> [OpenSearch Re:invent] Adds observability change for application_analytics

- config/playground/helm/dev/helm-opensearch-dashboards.yaml
- config/playground/helm/dev/helm-opensearch.yaml
- config/playground/helm/preview/helm-opensearch.yaml
- config/playground/helm/prod/helm-opensearch.yaml
This change adds additional permission to allow anonymous user to view security analytics dashboards, and tested that adding sample data in addition would solve all pop up errors
#105 
- [x ] Commits are signed per the DCO using --signoff 
> Grant permission for anonymous user for Security Analytics plugin

- config/playground/helm/preview/helm-opensearch-dashboards.yaml
Use private image which include observability sort fixes.
#109 
> [Opensearch Reinvent] Use private image which include observability sort fixes

- config/playground/helm/preview/helm-opensearch-dashboards.yaml
Signed-off-by: Lu Yu <nluyu@amazon.com>
change image to 2.4.0-11212022
N/A
> change image

- config/playground/helm/preview/helm-opensearch-dashboards.yaml
Signed-off-by: Lu Yu <nluyu@amazon.com>
This change uses a newly built image contains change from the branch asked by requester
[#115 ]
> update image for reinvent

- .github/workflows/functional-test-template.yml
Signed-off-by: Kristen Tian <tyarong@amazon.com>
Given I created the dashboard cloned from another sample dashboard, it will complain for overrides. Due to I didn't change existing visualization configuration, so this overriding will not cause issues.
> Add overwrite flag for MD ds

- .github/workflows/deployment-template.yml
- config/playground/helm/dev/helm-opensearch-dashboards.yaml
- config/playground/helm/searchapps/helm-opensearch-dashboards.yaml
Update GA version for dev and searchapps 
#142 
> [Playground] Change dev and searchapps configuration for new GA version

- config/playground/helm/preview/helm-opensearch-dashboards.yaml
- config/playground/helm/preview/helm-opensearch.yaml
Update observability cluster to 2.5 and add keystore for observability metrics
#145 
> [Playground] Update observability cluster to 2.5 and add keystore

- .github/workflows/deployment-template.yml
- .github/workflows/os-osd-deployment.yml
- config/playground/helm/ml/helm-machinelearning.yaml
- config/playground/helm/ml/helm-opensearch-dashboards.yaml
- config/playground/helm/ml/helm-opensearch.yaml
Adding ml playground and enable machinelearning data type
#141 
> [Playground ML] Adding ml playground

- .github/workflows/deployment-template.yml
- .github/workflows/os-osd-deployment-scheduled.yml
- config/playground/helm/observability/helm-opensearch-dashboards.yaml
- config/playground/helm/observability/helm-opensearch.yaml
Adding observability playground 
#149 
> [Playground observability] Adding observability playground

- .github/workflows/deployment-template.yml
- config/playground/helm/dev/helm-machinelearning.yaml
Adding machine learning data node to dev environment which will be used for 2.6 release 
#154 
> [Playground dev] Adding machine learning data node for dev

- .github/workflows/deployment-template.yml
- config/playground/helm/dev/helm-opensearch-dashboards.yaml
- config/playground/helm/prod/helm-machinelearning.yaml
- config/playground/helm/prod/helm-opensearch-dashboards.yaml
Release 2.6.0 for the playground, the OpenSearch 2.6.0 release at 02/28/2023. This PR is preparing for the 2.6.0 release.
#159 
> [Playground - Prod] Release 2.6.0 for the playground

- config/playground/helm/ml/helm-opensearch-dashboards.yaml
- config/playground/helm/observability/helm-opensearch-dashboards.yaml
- config/playground/helm/preview/helm-opensearch-dashboards.yaml
- config/playground/helm/searchapps/helm-opensearch-dashboards.yaml
update GA to 2.6.0 for scheduled cluster.
#160 
> [OpenSearch Playground] Update GA to 2.6.0 for scheduled cluster

- config/playground/helm/ml/helm-machinelearning.yaml
- config/playground/helm/ml/helm-opensearch.yaml
Add ML profile API permission for anonymous user
#168 
> [Playground -ml] Add ML profile API permission for anonymous user

- config/playground/helm/ml/helm-machinelearning.yaml
- config/playground/helm/ml/helm-opensearch.yaml
Adjust cpu number to fix development failure
> Adjust cpu number to fix development failure

- .github/workflows/os-osd-deployment-scheduled.yml
- .github/workflows/os-osd-deployment.yml
- config/playground/helm/dev/helm-machinelearning.yaml
- config/playground/helm/dev/helm-opensearch-dashboards.yaml
- config/playground/helm/dev/helm-opensearch.yaml
- config/playground/helm/ml/helm-machinelearning.yaml
- config/playground/helm/ml/helm-opensearch-dashboards.yaml
- config/playground/helm/ml/helm-opensearch.yaml
- config/playground/helm/observability/helm-opensearch-dashboards.yaml
- config/playground/helm/observability/helm-opensearch.yaml
- config/playground/helm/preview/helm-opensearch-dashboards.yaml
- config/playground/helm/preview/helm-opensearch.yaml
- config/playground/helm/prod/helm-machinelearning.yaml
- config/playground/helm/prod/helm-opensearch-dashboards.yaml
- config/playground/helm/prod/helm-opensearch.yaml
- config/playground/helm/searchapps/helm-opensearch-dashboards.yaml
- config/playground/helm/searchapps/helm-opensearch.yaml
Disabling multiple datasource from playground
N/A
> [OpenSearch Playground] Disabling multiple datasource from playground

- .github/workflows/os-osd-deployment.yml
- config/playground/helm/dev/helm-opensearch-dashboards.yaml
- config/playground/helm/dev/helm-opensearch.yaml
- config/playground/helm/ml/helm-opensearch-dashboards.yaml
- config/playground/helm/ml/helm-opensearch.yaml
- config/playground/helm/observability/helm-opensearch-dashboards.yaml
- config/playground/helm/preview/helm-opensearch-dashboards.yaml
- config/playground/helm/prod/helm-opensearch-dashboards.yaml
- config/playground/helm/prod/helm-opensearch.yaml
- config/playground/helm/searchapps/helm-opensearch-dashboards.yaml
> Release 2.7.0

- config/playground/helm/searchapps/helm-opensearch-dashboards.yaml
- config/playground/helm/searchapps/helm-opensearch.yaml
Update search apps playground docker image to use staging repo
N/A
> Update search apps playground docker image

- config/playground/helm/searchapps/helm-opensearch-dashboards.yaml
Disable GA on search apps playground ]
> Disable GA on search apps playground

- config/playground/helm/dev/helm-machinelearning.yaml
- config/playground/helm/dev/helm-opensearch-dashboards.yaml
- config/playground/helm/dev/helm-opensearch.yaml
- config/playground/helm/ml/helm-machinelearning.yaml
- config/playground/helm/ml/helm-opensearch-dashboards.yaml
- config/playground/helm/ml/helm-opensearch.yaml
- config/playground/helm/observability/helm-opensearch-dashboards.yaml
- config/playground/helm/preview/helm-opensearch-dashboards.yaml
- config/playground/helm/prod/helm-machinelearning.yaml
- config/playground/helm/prod/helm-opensearch-dashboards.yaml
- config/playground/helm/prod/helm-opensearch.yaml
> [OpenSearch Playground] 2.8.0 Release

- .github/CODEOWNERS
- MAINTAINERS.md
Adding Himanshu to maintainers 
N/A
> Adding Himanshu to maintainers

- .github/CODEOWNERS
- MAINTAINERS.md
Changing Github accout for Himanshu
> Changing Github accout for Himanshu

- config/playground/helm/dev/helm-opensearch-dashboards.yaml
- config/playground/helm/prod/helm-opensearch-dashboards.yaml
> [Playground] 2.9.0 release

- .github/workflows/deployment-template.yml
- .github/workflows/os-osd-deployment-scheduled.yml
- .github/workflows/os-osd-deployment.yml
- config/playground/helm/dev/helm-opensearch.yaml
- config/playground/helm/observability/helm-opensearch.yaml
* This CR adds plugins.query.datasources.encryption.masterkey to opensearch.yml for configuring datasources in sql plugin.
Since this value of this key is confidential, we have leveraged Github secrets to insert the master key during runtime.
* Unless we found a better way to provide secrets in opensearch.yml config[https://github.com/opensearch-project/helm-charts/issues/458], we will leverage Github secrets.
* we will experiment with dev and observability clusters before and then we will move this to Production playground.
For more information on following Developer Certificate of Origin and signing off your commits, please check …
> Add  plugins.query.datasources.encryption.masterkey

- config/playground/helm/dev/helm-opensearch-dashboards.yaml
- config/playground/helm/preview/helm-opensearch-dashboards.yaml
- config/playground/helm/prod/helm-opensearch-dashboards.yaml
[OpenSearch Playground] Release 2.10.0
> [OpenSearch Playground] Release 2.10.0

- .github/workflows/os-osd-deployment.yml
- config/playground/helm/dev/helm-machinelearning.yaml
- config/playground/helm/dev/helm-opensearch-dashboards.yaml
- config/playground/helm/dev/helm-opensearch.yaml
- config/playground/helm/ml/helm-machinelearning.yaml
- config/playground/helm/ml/helm-opensearch.yaml
- config/playground/helm/observability/helm-opensearch.yaml
- config/playground/helm/preview/helm-opensearch-dashboards.yaml
- config/playground/helm/preview/helm-opensearch.yaml
- config/playground/helm/prod/helm-machinelearning.yaml
- config/playground/helm/prod/helm-opensearch-dashboards.yaml
- config/playground/helm/prod/helm-opensearch.yaml
- config/playground/helm/searchapps/helm-opensearch-dashboards.yaml
- config/playground/helm/searchapps/helm-opensearch.yaml
> [Playground] Patching playground

- config/playground/helm/dev/helm-opensearch-dashboards.yaml
- config/playground/helm/preview/helm-opensearch-dashboards.yaml
- config/playground/helm/prod/helm-opensearch-dashboards.yaml
- config/playground/helm/searchapps/helm-opensearch-dashboards.yaml
* This one is to promote OSD 2.11 to Playground
N/A
> 2.11 release

- config/playground/helm/prod/helm-machinelearning.yaml
- config/playground/helm/prod/helm-opensearch-dashboards.yaml
- config/playground/helm/prod/helm-opensearch.yaml
> 2.12 release for prod

- config/playground/helm/prod/helm-opensearch.yaml
Fix the format issue in helm-opensearch.yml
> Fix the format issue

- .github/CODEOWNERS
- MAINTAINERS.md
Update the maintainer list. We followed the process of sending an email to all maintainers to inform them of these changes.
N/A
> [Dashboards-anywhere] Update maintainer list

- .github/workflows/README.md
- .github/workflows/trigger-future-deployment.yml
- config/playground/helm/future/helm-opensearch-dashboards.yaml
- config/playground/helm/future/helm-opensearch.yaml
Adding a future playground to the deployment pipeline. It will be utilized by the `workflow_dispatch` GitHub action and triggered on demand. We have added a couple of input parameters that allow for either a fresh deployment or an upgrade.
N/A
> [Future-Playground] Adding future playground to deployment pipeline

- config/playground/helm/dev/helm-machinelearning.yaml
- config/playground/helm/dev/helm-opensearch-dashboards.yaml
- config/playground/helm/dev/helm-opensearch.yaml
support 2.13.0 release.
We are using a custom build https://hub.docker.com/r/peterzhuamazon/opensearch-dashboards/tags?page=1&name=2.13.0-special which contains the change for https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6321
> support 2.13.0 release for dev

- config/playground/helm/prod/helm-machinelearning.yaml
- config/playground/helm/prod/helm-opensearch-dashboards.yaml
- config/playground/helm/prod/helm-opensearch.yaml
> support 2.13.0 in prod

- config/playground/helm/dev/helm-machinelearning.yaml
- config/playground/helm/dev/helm-opensearch-dashboards.yaml
- config/playground/helm/dev/helm-opensearch.yaml
> [Playground Dev Build]upgrade to 2.14.0

- config/playground/helm/prod/helm-machinelearning.yaml
- config/playground/helm/prod/helm-opensearch-dashboards.yaml
- config/playground/helm/prod/helm-opensearch.yaml
> [Playground Prod Build]2.14.0 release prod

- config/playground/helm/dev/helm-machinelearning.yaml
- config/playground/helm/dev/helm-opensearch-dashboards.yaml
- config/playground/helm/dev/helm-opensearch.yaml
Upgrade to 2.15.0 for dev env
NA
> upgrade to 2.15.0 for dev env

- config/playground/helm/dev/helm-machinelearning.yaml
- config/playground/helm/dev/helm-opensearch-dashboards.yaml
- config/playground/helm/dev/helm-opensearch.yaml
> Bump Dashboards to 2.16 for Dev Env

- config/playground/helm/prod/helm-machinelearning.yaml
- config/playground/helm/prod/helm-opensearch-dashboards.yaml
- config/playground/helm/prod/helm-opensearch.yaml
This PR bumps Dashboards to 2.16
N/A
> Bump Dashboards to 2.16 for prod env

- config/playground/helm/dev/helm-machinelearning.yaml
- config/playground/helm/dev/helm-opensearch-dashboards.yaml
- config/playground/helm/dev/helm-opensearch.yaml
This change bump version to 2.17 for dev
NA
> bump version for dev to 2.17

- config/playground/helm/prod/helm-machinelearning.yaml
- config/playground/helm/prod/helm-opensearch-dashboards.yaml
- config/playground/helm/prod/helm-opensearch.yaml
This change bumps version to 2.17.0 for prod
NA
> bump version to 2.17.0 for prod

- config/playground/helm/dev/helm-machinelearning.yaml
- config/playground/helm/dev/helm-opensearch-dashboards.yaml
- config/playground/helm/dev/helm-opensearch.yaml
> Bump Dashboards to 2.18 for dev env

- config/playground/helm/prod/helm-machinelearning.yaml
- config/playground/helm/prod/helm-opensearch-dashboards.yaml
- config/playground/helm/prod/helm-opensearch.yaml
This PR bumps Dashboards to 2.18
> Bump Dashboards to 2.18 for prod env
